       IDENTIFICATION DIVISION.
       PROGRAM-ID. TEST4.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 COUNTER PIC 9(2) VALUE 0.
       PROCEDURE DIVISION.
           PERFORM UNTIL COUNTER > 5
               DISPLAY COUNTER
               ADD 1 TO COUNTER
           STOP RUN.
