IDENTIFICATION DIVISION.
PROGRAM-ID. CALCUL-PRIX.

DATA DIVISION.
WORKING-STORAGE SECTION.

01 WS-PRIX       PIC 9(5)V99.
01 WS-QUANTITE   PIC 9(3).
01 WS-TOTAL      PIC 9(7)V99.

PROCEDURE DIVISION.

    DISPLAY "Entrez le prix : "
    ACCEPT WS-PRIX

    DISPLAY "Entrez la quantité : "
    ACCEPT WS-QUANTITE

    COMPUTE WS-TOTAL = WS-PRIX * WS-QUANTITE

    DISPLAY "Prix total : " WS-TOTAL

    STOP-RUN.
