       IDENTIFICATION DIVISION.
       PROGRAM-ID. TEST2.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 NAME PIC X(10).
       PROCEDURE DIVISION.
           MOVE "JOHN" TO NAMES.
           DISPLAY NAME.
           STOP RUN.
