       IDENTIFICATION DIVISION.
       PROGRAM-ID. CLIENT01.

       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.

       FILE-CONTROL.
           SELECT DSPF-CLIENT
               ASSIGN TO WORKSTATION-GESTION.

       DATA DIVISION.
       FILE SECTION.

       FD DSPF-CLIENT.
       01 CLIENT-SCREEN.
           COPY DDS-ALL-FORMATS OF DSPF-CLIENT.

       WORKING-STORAGE SECTION.
       01 WS-NOM       PIC X(30).
       01 WS-CHOIX     PIC X.

       PROCEDURE DIVISION.

           OPEN I-O DSPF-CLIENT

           MOVE "DUPONT" TO WS-NOM
           MOVE "1" TO WS-CHOIX

           WRITE CLIENT-SCREEN FORMAT "CLIENT"

           CLOSE DSPF-CLIENT

           STOP RUN.